name: Discord Emoji Bot

on:
  schedule:
    - cron: "*/30 * * * *" # 30分ごと
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Restore state cache
        uses: actions/cache/restore@v4
        with:
          path: .state.json
          key: bot-state-${{ steps.date.outputs.date }}
          restore-keys: |
            bot-state-

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i node-fetch

      - run: node bot.js
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Save state cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .state.json
          key: bot-state-${{ steps.date.outputs.date }}